### ISSUE TITLE
Media from Reposts and Quotes not retrieved by API

### ISSUE THREAD

**Issue by CodedOre** [CodedOre/NewCaw#18]
A point which may need to be adressed at some point.

While `TwitterLegacy` displays media from a repost or quote, `Twitter` does not:

| `TwitterLegacy` | `Twitter` |
| --- | --- |
| ![Repost displayed with `TwitterLegacy` backend](https://user-images.githubusercontent.com/47981497/141646691-8bc76a56-5319-42c0-816b-b4cf43d93c67.png) | ![Repost displayed with `Twitter` backend](https://user-images.githubusercontent.com/47981497/141646689-4d07b5f3-3c44-4d72-ab1e-0917bcdb6e71.png) |

The issue here is simple: Unlike the old API, the new API don't returns the includes for an `referenced_tweet`, apart from (optionally) the author.

So, we might need to adress this. We could read the media keys (which are noted) and then issue a call for the original post to retrieve the media (and have a problem with hitting the tweet cap faster).

**Comment by CodedOre** [comment]
Just a note: This would effect all includes, including mentioned users, media and polls.

**Comment by IBBoard** [comment]
That's… bad. Are there really no options to enable them? Because that seems like rather fundamental content! Do things like `tweet.fields` only apply to tweets and not the inner RT (and presumably quoted tweet)?

**Comment by CodedOre** [comment]
`tweet.fields` are applied to `referenced_tweet` as well. However, media, users and polls are separate objects only referenced by their id in a tweet object and need to be called with the `expansions` argument, and these are only applied to top-level tweets, not the referenced one, which is why they have an additional `referenced_tweets.id.author_id` so you can at least get the user object for the original poster.

**Comment by CodedOre** [comment]
This issue is resolved. We now only request the id of the referenced tweet and then load it when needed. This way we get the includes as well.

This also solves the issue that in a retweet of an quote the quoted tweet is not pulled.
