### ISSUE TITLE
Better feedback on a failing test

### ISSUE THREAD

**Issue by CodedOre** [CodedOre/NewCaw#22]
The tests currently use `assert` to check if the values from the parsed objects are the same as the check object.

However, as Vala compiles to C first, when an assert fails it's put's out the assert as compile from C, which results often in it displaying that the variables `__tmp*__` were not the same.

It might be worth an discussion on how we can improve the feedback, so that it's better to see which variables didn't match and how they differ.

**Comment by IBBoard** [comment]
I hadn't noticed that. But then I don't run the tests all that often 😁 Exceptions normally print the Vala lines rather than the C code, so is this an issue in Vala's bindings rather than anything that we can fix?

**Comment by CodedOre** [comment]
There might be something that could be done by Vala, but at the end `assert` is an GLib function. Will ask this on the Vala repo tomorrow.

Apart from that, another reason I thought about a custom test function was that we can also directly an diff between the tested variables, so one can directly see the differences.

**Comment by CodedOre** [comment]
Changed this in adc59506decbf2a5c0fa05f594cfca1e9774f95c to a custom function.

This has the benefit that we can display the difference between the check and the actual value, and also I set that it don't exit but runs through the other tests as well, so I think this is now resolved.
