### ISSUE TITLE
Consider using Blueprints for UI files

### ISSUE THREAD

**Issue by CodedOre** [CodedOre/NewCaw#23]
Recently, James Westman has released [Blueprint](https://jwestman.pages.gitlab.gnome.org/blueprint-compiler/), an language for defining UI-files with an non-xml syntax.
It works similar to Vala, compiling it's syntax to the UI-Builder XML which then is used by GTK.

Using Blueprint would add an dependency, but would allow to define the UI files in a Vala-like syntax, making them more readable.

**Comment by IBBoard** [comment]
Interesting… I'm used to just hacking the Glade files by hand and hoping I got it right 😁

Not having to type as much is probably good, and JSON-style markup is all the rage these days. It'll take some getting used to, but it might be an improvement if it supports everything that we need. And as you say, we're already doing the transpiling of Vala into C, so transpiling another thing isn't that bad 🙂

**Comment by CodedOre** [comment]
I just ported all UI files to Blueprint.

Some were ported by hand, some were done using the porting tool, but I think it should all work as expected.

**Comment by CodedOre** [comment]
And it seems like I run into [this issue](https://gitlab.gnome.org/jwestman/blueprint-compiler/-/issues/18). So, with f40156fa53c79598e1fefea203ad8a867f25dcb0 I've added a dummy `.ui` file so meson is less confused...
