### ISSUE TITLE
Standardize the loading of Media

### ISSUE THREAD

**Issue by CodedOre** [CodedOre/NewCaw#24]
We have different places where we load media:
- [`UserAvatar`](https://github.com/CodedOre/NewCaw/blob/main/src/Widgets/UserAvatar.vala) for the user avatar
- [`MediaPreviewItem`](https://github.com/CodedOre/NewCaw/blob/main/src/Media/MediaPreviewItem.vala) for the preview in a post
- [`MediaDisplayItem`](https://github.com/CodedOre/NewCaw/blob/main/src/Media/MediaDisplayItem.vala) for the main media display
- [`ProfileCard`](https://github.com/CodedOre/NewCaw/blob/main/src/Content/ProfileCard.vala) for the profile header

All these widget perform a similar task: Get the `MediaLoader`, begin loading and, when it's done, place the loaded media inside a widget capable of holding a `Gdk.Paintable`, either `Gtk.Picture`, `CroppedPicture` and (eventually) `ScrollablePicture`.

Since these are at least 10 lines of code almost identical in each one I though if we could (and should) combine this into a universal method used by all of them, and how to ideally accomplish this.

**Comment by IBBoard** [comment]
Makes sense to me. If you can pass in a URL, a proxy (because media in DMs may need OAuth) and a surface/Paintable to put it on then I don't see why you couldn't standardise it 🙂
