### ISSUE TITLE
App opens into a blank screen

### ISSUE THREAD

**Issue by SilverMarcs** [CodedOre/NewCaw#25]
Built the app via gnome-builder and running it launches an empty window. Is this intended/known behaviour at this stage of development?

**Comment by CodedOre** [comment]
It is intended behaviour.

I currently use demo code to test the stuff I'm writing, as I haven't implement the code for loading information from the API.
See [About Building and Contributing](https://github.com/CodedOre/NewCaw/discussions/4) for a patch file with the demo code.
