### ISSUE TITLE
Keep an eye on librest

### ISSUE THREAD

**Issue by CodedOre** [CodedOre/NewCaw#27]
NewCaw is using libsoup 3.0 for loading media, which apparently is quite a new release.
librest, which will be likely used for making the API calls however does not have a stable version supporting this yet, but this should be resolved [soon](https://discourse.gnome.org/t/status-of-librest/8599/2).

My main concern then is native packages:
As of now, librest either compiles with support for libsoup 2.0 or 3.0, [not both at the same time](https://gitlab.gnome.org/GNOME/librest/-/blob/0e7f638c3b2f5d987eaeca0d05b246bc03da6b50/meson.build#L44-54), so we should keep an eye on how different distributions will handle this.

**Comment by IBBoard** [comment]
As if moving to libadwaita wasn't going to cause enough fun for "which distro supports this?" 😄 Hopefully there's some consensus by the time NewCaw gets close to being ready 🙂

**Comment by fabiscafe** [comment]
I think this can be closed, we now have libsoup3 with [librest 0.9.1](https://gitlab.gnome.org/GNOME/librest/-/tags/0.9.1). BTW [Please ignore the 1.0.0 release, this was a wrong tagged release of 0.9.0](https://gitlab.gnome.org/GNOME/librest/-/issues/17).
