### ISSUE TITLE
Combine `User` and `Profile`

### ISSUE THREAD

**Issue by CodedOre** [CodedOre/NewCaw#29]
While working on the `Account` class, I came to the conclusion that we could combine the `User` and `Profile` class into one.

The reasoning behind this is the following: When loading data for the `TwitterLegacy` and `Mastodon` backend, we always get all information anyway, so we could just store all information, saving us from loading it again when we want to show the `ProfileView`. It would also reduce code repetition, as due to the class structure we need to repeat the code from the `User` constructor in the `Profile` one.

**Comment by IBBoard** [comment]
Given the pain I had this weekend when picking through the various different places that fetched user details and retrieved and loaded the avatar in different ways, just so that I could handle withheld accounts, I think this sounds like a sensible idea 🙂

**Comment by CodedOre** [comment]
Is now done with commit 8a70f04, closing it.
