### ISSUE TITLE
NewCaw shares tray with Cawbird

### ISSUE THREAD

**Issue by IBBoard** [CodedOre/NewCaw#41]
Just poking NewCaw and found that it's sharing the tray with my existing Cawbird app in Gnome.

On the one hand, it makes sense because it's just the new Cawbird.

On the other hand, it's 1.x and 2.x and it's a big change, rather than 1.3.x and 1.4.x.

Not sure whether we need to fix it or not.

**Comment by CodedOre** [comment]
That's probably something to be expected. The desktop file contains the same name and is store under (almost) the same name...

The question is if we want to make development builds to be split up. I already set the application id to `uk.co.ibboard.Cawbird.Devel` when building with debug mode, so it would make sense to do this on the other places with the id as well.

**Comment by CodedOre** [comment]
Alright, I finally got around to improve the build of desktop files and icons. If it works as expected we could close this.

Two notes:
- The data folder has now two desktop files, one for a release version and one for the development one. We should look if meson could append the development parts so we don't have two files.
- I also now have included the new icons from IBBoard/cawbird#452, I think we should use them in upcoming version.

**Comment by IBBoard** [comment]
+1 on using the new icon. We've not come up with a different name yet, and it makes more sense to switch with the new app rather than switching the existing app.

With the desktop file, it does support `.in` files for other things. I suspect there's also a workaround using templates and output paths, but that might not be as clear. I've never tried, though, and I didn't always find the Meson documentation all that helpful.
