### ISSUE TITLE
Very wide tweets force a minimum width on NewCaw

### ISSUE THREAD

**Issue by IBBoard** [CodedOre/NewCaw#42]
It's basically baedert/corebird#514 all over again. If someone includes a long and unbreakable string in the tweet then Cawbird can suddenly become extra-wide and not go any narrower.

Cawbird fixes this with a slightly ugly work-around - the [ChildSizedScroller](https://github.com/IBBoard/cawbird/blob/master/src/widgets/ChildSizedScroller.vala)

Example tweet: https://twitter.com/IBBTwtr/status/1385978054254764035

**Comment by CodedOre** [comment]
Not sure I can reproduce this here:

![non-narrow-narrow](https://user-images.githubusercontent.com/47981497/163467200-279dc181-bb53-432a-ae21-a837673e31df.png)

Is this text not wrapped on your system?

**Comment by IBBoard** [comment]
It does wrap (because Pango does better than it used to) but the character is much wider than the placeholder that you're seeing. 

![image](https://user-images.githubusercontent.com/388582/163606040-8e830c55-4c6a-44b8-a348-56a52200ed0d.png)

(As an aside: Huh, I need to fix my Adwaita overrides, because that border isn't supposed to be there!)

**Comment by CodedOre** [comment]
So, if it is avoidable I would like to avoid to add an `ScrolledWindow` to each label...
For now I'm going to say that we can look into this at an later point.

**Comment by IBBoard** [comment]
We could use the `ellipsize` setting, which is also better than it was. But  that then causes the [Royal Society of Chemistry tweet ](https://twitter.com/RoySocChem/status/928200456760852480) to go from 
![image](https://user-images.githubusercontent.com/388582/163608463-c675f856-e979-43ea-bb25-802c73f94df1.png)
to
![image](https://user-images.githubusercontent.com/388582/163608500-1337085b-c60b-4d42-ace2-58c01c97670d.png)
(So it over-truncates when it could be wrapping)

**Comment by CodedOre** [comment]
Or we could allow `Gtk.Label` to wrap on characters when the place is not sufficient:

![orderly-wrapped](https://user-images.githubusercontent.com/47981497/163620034-b9e963fd-5916-470f-89d0-0fea7785be9a.png)

00460b46a27a6a01241602b1047db1dbc44a8570 should hopyfully fix this.

> (As an aside: Huh, I need to fix my Adwaita overrides, because that border isn't supposed to be there!)

Which border?

**Comment by IBBoard** [comment]
Yeah, that works! I'm sure there was a reason that I didn't use it before. Like maybe it was a bit too quick to break inside a word rather than just moving the whole word down a line. But it fixes the one that's just odd characters as well.

The borders that I'm seeing are around the username. It seems to be because it's a `button.flat` widget. The inspector is being annoying and not telling me where the rule comes from, though, so I don't know if it's my override causing it or not.

**Comment by CodedOre** [comment]
Well, we can reopen this should we find an issue with this solution, but closing it for now.

> The borders that I'm seeing are around the username. It seems to be because it's a button.flat widget. The inspector is being annoying and not telling me where the rule comes from, though, so I don't know if it's my override causing it or not.

That's probably line 25 in your [`gtk.minimal`](https://dev.ibboard.co.uk/repos/other/Adwaita-Dark-Green/file/tip/gtk-4.4/gtk-minimal.css):

```
list button { border: 1px @borders solid; }
```

**Comment by IBBoard** [comment]
> That's probably line 25 in your [`gtk.minimal`](https://dev.ibboard.co.uk/repos/other/Adwaita-Dark-Green/file/tip/gtk-4.4/gtk-minimal.css) (and yes, the username is using a flat button for selection):
> 
> ```
> list button { border: 1px @borders solid; }
> ```

Yeah, that'd do it 😁 But if I don't have that there then there's some other situation that looks stupid and ugly because you can't see that there's a button inside lists. I'll look at it again. Thanks for looking for it.

**Comment by IBBoard** [comment]
Also, I checked and I am using `word-char` for wrapping, so Pango must be doing better and Cawbird has now [ditched the `ScrolledWindows` as well](https://github.com/IBBoard/cawbird/commit/cb40e215f7bc61048b14ab1c9e3e96ac716f2e55)
