### ISSUE TITLE
Support Device-local subscriptions and groups like Fritter

### ISSUE THREAD

**Issue by marc0x1** [CodedOre/NewCaw#52]
[Fritter Github](https://github.com/jonjomckay/fritter )
Fritter is an FOSS android app that let you access a feed view without having a twitter account.
For privacy-minded person, it could be a killer feature.

Features that Fritter support without an account:

- [ ] -     Device-local subscriptions and groups, Newpipe-style, including a feed view
- [ ] -     Device-local saving of tweets, allowing offline reading
- [ ] -     Viewing profiles
- [ ] -     Viewing tweets, and tweet replies, threads and conversations
- [ ] -     Viewing and downloading pictures, videos and GIFs in tweets
- [ ] -     Searching for tweets and users
- [ ] -     Viewing trending topics
- [ ] -     Supports opening twitter.com links directly

**Comment by CodedOre** [comment]
I think there are three separate points in this issue. 

1. Allow the use of Cawbird without an account
2. Allow to cache post for offline-reading
3. Open `twitter.com` links directly in Cawbird

I comment about point 1 and 2 later, but for point 3 I already have to say that it can't be implemented as of now. While we can define an uri protocol to redirect to the app (like `cawbird://`), there is no standard to only redirect a link to a specific website.

**Comment by marc0x1** [comment]
Should I open 3 different issue?
Regarding point 3, [FreeTube](https://github.com/FreeTubeApp/FreeTube) is a Linux frontend for Youtube that allow to open links directly in app, thanks to [Privacy Redirect ](https://github.com/SimonBrazell/privacy-redirect) ( a browser extension ),
As far as I know the extension convert the url into a uri supported by Freetube.

**Comment by CodedOre** [comment]
> Should I open 3 different issue?

Yes, you could do that. 

> Regarding point 3, [FreeTube](https://github.com/FreeTubeApp/FreeTube) is a Linux frontend for Youtube that allow to open links directly in app, thanks to [Privacy Redirect ](https://github.com/SimonBrazell/privacy-redirect) ( a browser extension ),
> As far as I know the extension convert the url into a uri supported by Freetube.

I see. I think adding more options to the `cawbird://` is something that could be implemented, so other apps could call Cawbird using that.
