### ISSUE TITLE
Cannot authenticate with Twitter

### ISSUE THREAD

**Issue by IBBoard** [CodedOre/NewCaw#57]
Since I'm using Mastodon more now, I thought I should get involved in NewCaw and see if we can get things moving 🙂

I can successfully authenticate with Mastodon (hachyderm.io) and it was surprisingly easy (except for the bit where I'm running a local build, so the URL handler isn't installed, so I had to manually run `build/src/cawbird cawbird://authenticate?…`.

Twitter is being more difficult, though. I currently get "Something went wrong - you weren't able to give access to this app".

I'm using Cawbird's OAuth2 key (but I thought I normally needed the secret as well?). I had it working before, but that was months ago with a different Meson config!

![Screenshot of Twitter's error](https://user-images.githubusercontent.com/388582/202871295-6975427d-95a1-4e0a-9409-6cdb17e6dcc5.png)

Is it broken, or did I do something wrong? Or is it the OAuth URL validation kicking in, and the Cawbird 1.0 OAuth2 key isn't valid?

**Comment by CodedOre** [comment]
> I'm using Cawbird's OAuth2 key (but I thought I normally needed the secret as well?).

With OAuth 2.0, it's normally discouraged to include the client secret in an "native application", so you don't need it with Twitter.

> Is it broken, or did I do something wrong? Or is it the OAuth URL validation kicking in, and the Cawbird 1.0 OAuth2 key isn't valid?

It does work with my key, so much I can say. We'll have to see for how much longer, given the current status of Twitter.
So I would think it has to do with the provided client id.

**Comment by CodedOre** [comment]
I think I might know the reason:

Twitter only accepts the authentication url if you are giving it an redirect uri set in the application settings. Otherwise it shows this screen. Just remembered that I once had this issue because I had made an typo.

You need to ensure that these two uri are set as redirect in the application settings in the Developer Portal on Twitter: `cawbird://authenticate` and `https://example.com`, the latter is the current "fallback" for out-of-band.

**Comment by IBBoard** [comment]
Looks like I needed to generate a new "OAuth 2 Client ID", which is different from and longer than the older keys that I have (which must be OAuth 1 key/secret pairs) - 34 characters vs 25.

Now I get the authentication page, but it's giving me a "something went wrong" when I hit the authorise button.

![image](https://user-images.githubusercontent.com/388582/210063777-4b990887-4525-4202-bccf-86487be5f0a2.png)

**Comment by IBBoard** [comment]
Ahah! It did the "something went wrong" because I cancelled it. But if I check the console carefully then there's a message about the unknown protocol!

But I do get to report a bug because hitting "Retry authentication" in the app gets the "something went wrong" page 🙂
