### ISSUE TITLE
Parsing error on &nbsp;

### ISSUE THREAD

**Issue by IBBoard** [CodedOre/NewCaw#72]
Apparently posts can use HTML entities, but we parse them as XML and so the named entities don't exist.

That results in a crash with the following in the logs:
```
Entity: line 1: parser error : Entity 'nbsp' not defined
<text><p>A U.S. No Fly list with&nbsp;over 1.5 million records of banned flyers 
                                      ^
Entity: line 1: parser error : Entity 'nbsp' not defined
d publicly on a hacking forum. BleepingComputer has confirmed, the list is&nbsp;
                                                                               ^
Entity: line 1: parser error : Entity 'nbsp' not defined
 BleepingComputer has confirmed, the list is&nbsp;the same TSA No Fly list&nbsp;
                                                                               ^
Entity: line 1: parser error : Entity 'nbsp' not defined
list is&nbsp;the same TSA No Fly list&nbsp;that was discovered recently on&nbsp;
                                                                               ^
Entity: line 1: parser error : Entity 'nbsp' not defined
Fly list&nbsp;that was discovered recently on&nbsp;an unsecured CommuteAir&nbsp;
                                                                               ^

(cawbird:14423): cawbird-ERROR **: 19:19:23.481: TextParser.vala:291: Failed to parse text to XML tree!
```

Problem toot: https://hachyderm.io/@BleepingComputer@infosec.exchange/109778043935225452 (original https://infosec.exchange/@BleepingComputer/109778043876337854)

**Comment by IBBoard** [comment]
Quick fix is to add the following in `parse_text()` in `lib/Mastodon/Utils/TextParser.vala`:
```
parsed_text = parsed_text.replace ("&nbsp;", "\u00A0");
```
But I'm sure we'll end up hitting other ones! `&raquo;`? Looks like we're safe on some of the common ones, though, because [&amp; etc are in XML](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#List_of_predefined_entities_in_XML).

**Comment by CodedOre** [comment]
Does `Markup.escape` properly escape these symbols, so they are safe for Pango?

If so, we could just drop this into the [default block](https://github.com/CodedOre/NewCaw/blob/main/lib/Mastodon/Utils/TextParser.vala#L96-L99) of `TextParser`.

**Comment by IBBoard** [comment]
From reading [the docs](https://valadoc.org/glib-2.0/GLib.Markup.escape_text.html)… possibly not in the way we need.

> Less than, greater than, ampersand, etc. are replaced with the corresponding entities. This function would typically be used when writing out a file to be parsed with the markup parser.

My reading of that is that it'll replace `&nbsp;` with `&amp;nbsp;`, which will then render as a visible `&nbsp;` for users rather than acting as a non-breaking space. I've seen that in other languages.

We don't want to escape. We want to unescape _some_ entities. Or un-encode them. Or something.

But I'm about to log off, so I've not tested it.

**Comment by CodedOre** [comment]
Having looked at it today, it seems like I've misread a bit where the problem comes from. Somehow thought it was related to `Gtk.Label` and Pango...

Anyway, since I don't know of a better solution, I have added your fix in `TextParser.

**Comment by IBBoard** [comment]
Poking around this (because I don't like ugly solutions!), I think our only option is to include extra DTD information and reference the [HTML/MathML DTD](https://www.w3.org/2003/entities/2007/htmlmathml-f.ent).

I don't know how we'd include the file and reference it, though. Relying on HTTP requests for XML parsing is a bad idea!

**Comment by CodedOre** [comment]
I think the current solution is the best one.
Even if we get the XML Parser to parse the DTD file, Pango doesn't understand `&nbsp;` anyway, so it would only move the issue to another place.

**Comment by IBBoard** [comment]
Ah yeah, I guess it would only fix the parsing. It wouldn't let us map them to the integer codes or the Unicode characters on its own.
